# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
  - R -q -e 'if (!requireNamespace("remotes") || "remotes" %in% old.packages()) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
dist: bionic
cache: packages
latex: false


# stages
stages:
- name: test
- name: full
  if: branch = master

# jobs
jobs:
  include:
  - stage: test
    r: devel
  - stage: full
    r: release
    env:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"
    - BUILD_PKGDOWN=true
  - os: osx
    r: release
  fast_finish: true

# apt-get packages (textshaping)
addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
